GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "boom",
    "author": "me",
    "url": "localhost",
    "likes": 10
}

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "hello",
    "name": "me",
    "password": "goodbye"
}