GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbGxvIiwiaWQiOiI2NzU0MGZjNjY1OTBhNTFhZGUxNjg3NWIiLCJpYXQiOjE3MzM1Njg2NjIsImV4cCI6MTczMzU3MjI2Mn0.j-i5etnAxJk3Ilv8PGE4K-IlxFDkuy_ZUe2T49exLM4

{
    "title": "boom",
    "author": "me",
    "url": "localhost",
    "likes": 10
}

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "hello",
    "name": "me",
    "password": "goodbye"
}

###

POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "hello",
    "name": "me",
    "password": "goodbye"
}

###